{% set name = "mysql-connector-python" %}
{% set version = "8.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: 52944d6fa84c903fd70723a47d2f8c3153c50ae91773f1584a7bd30606c58b35
  patches:
    - patches/0001-Typecast-password-to-const-char-explicitly-py3.patch
    - patches/0002-Fix-location-for-searching-mysql-headers-and-libs-on.patch
    - patches/0003-Fix-indentation-for-common-flags.patch
    - patches/0004-Revert-Fix-MacOS-wheels-platform-tag.patch
    - patches/0005-Replace-google-protobuf-string-with-std-string.patch
    - patches/0006-Delete-openssl-vendor-ed-libs-only-if-provided.patch

build:
  number: 2
  # VS 2008 is not supported for libprotobuf
  skip: True  # [py<38]
  skip: True  # [linux and s390x]
  ignore_run_exports:
    - libprotobuf
    - libstdcxx-ng

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch       # [not win]
    - m2-patch    # [win]
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - mysql {{ version }}  # [not win]
    - protobuf 5.29.3
    - libprotobuf 5.29.3
  run:
    - python
    - mysql  # [not win]
    - protobuf
  run_constrained:
    - dnspython >=1.16.0,<=2.3.0
    - python-gssapi >=1.6.9,<=1.8.2
    - deprecated >=1.2.6
    - typing-extensions >=3.7.4
    - zipp >=0.5

test:
  requires:
    - python
    - pip
  imports:
    - mysql
    - mysql.connector
  commands:
    - pip check
    - test -e `find . -iname _mysql_connector.*.so`  # [not win]
    # Not testing on windows as it's built without c extension due to lack of mysql package

about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-only WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Python driver for communicating with MySQL servers'

  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: https://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
