{% set name = "mysql-connector-python" %}
{% set version = "9.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: 68b4fab8f4cdfc765228335b28fa9da8e3353dfe77e74d12880d96dd6b9799e9

build:
  number: 0
  skip: True  # [py<39]
  ignore_run_exports_from:
    - {{ compiler('cxx') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch       # [not win]
    - m2-patch    # [win]
    - pkg-config
  host:
    - python
    - pip
    - setuptools
    - mysql-devel {{ version }}
    - mysql-client {{ version }}
  run:
    - python
  run_constrained:
    - dnspython ==2.6.1
    - python-gssapi ==1.8.3
    - fido2 ==1.1.2
    - opentelemetry-api==1.18.0
    - opentelemetry-sdk==1.18.0
    - opentelemetry-exporter-otlp-proto-http==1.18.0

test:
  files:
    - run_database_test.sh
    - database_test.py
  requires:
    - python
    - pip
    - mysql-server {{ version }}
    - mysql-client {{ version }} # For mysqladmin
  imports:
    - mysql
    - mysql.connector
  commands:
    - pip check
    - test -e `find . -iname _mysql_connector.*.so`  # [not win]
    - bash run_database_test.sh  # [not win]

about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-only WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Python driver for communicating with MySQL servers'

  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: https://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - synapticarbors
    - nehaljwani
