travis:
  secure:
    BINSTAR_TOKEN: sFMuRZfCvlzhdT0oWEmu7yBNp4yQ6tplPLs5w5pKZ+s16TalZ+UJfRn+AceUPKcDlAIHkr4R0GY/XxYUCSfZ67nTK3CXdXvy6FoSeAjZfiQ+MTn8PHT6bKccoXCJ+dabfScpLHwYSTR3vTcYy6T4brVUCWUZxTt6dfnrpMBjabFSG+HBV9GWy2r1m0RrgDFkUCR52JikNyOhr9rKCJ6TlZS43GYNJmTgbI6TxY++wx6+C3yWwTETI6lD34WZDDpkofucLqycMwiO2UpT/b9eNg5Ut+0uinRD3HNseOp4K96oZrb6xMEeN2BTK21JVyLf40PGS1GRystheOwjUDGbVVii/f31YJ31FY+HJTlcUVKLE8ttNXQnUZeIjI7R64JEclnV6jTjm+qCDGunyuyzyJCKolahFC6X0aWhEWPjxh2VVkP/jlMAleLIBO7D7+QKAH4TXpW1MC5CyQwblATyo5f68gmmpM/ig40ua25K5H4dL1A1SWsVgLWs+m/4v5d3lpokh/Qy70vdLRvPPSmYIrBTIOLQFKliBKQsXEILOFjpMkOXcPbjkp0BHrm4VH+1j/DIx8Y2bSoVdtU2Z+aAwnI5IQRej7D31KjwK+tnY4lpLTgZafx+sYZ/F3VX794iMfKnYwrU8GZQ2kGP2uhl5mlb4IHeC4wyOxJh7Epfrs0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
