travis:
  secure:
    BINSTAR_TOKEN: W6oEN8djzYIwu7SJh8D0oKR6Y7cmXM8SKE815PqUCsI8qB/aBVGeq1IEsqQ8lgNEONzT4sGWpueAPlVieTFMDYry+OfZGE/VnAcrfrtVmRZ1z3ANARRJHHrny02wmiLda/VN0HjzxdE4+k5hIBlhaCGVq9K0hnOx+DQkCmz6XrwppGfO8lFBXTPFg8A712I5LbBhI96s/yGe4SXdJ0Tvxqi7IrHKQf/M0m7rKSVxrIVV/bByJTOVs06Dwnie7shMN9AhRwcK/f7CoZeOlvbAr+P/i8rO1FCAfrSn5wsKxrVA2OIypp183BNRe7nnBwTvl7Y8s8+gIwaUxncx9lG+xzgUBl6QfOjffv5Ojph+oc1zLCJ/7sXokBxLlfQpXWQNJpXCs+gnTYWObg7tDTk1Cn16rctrFw7MG5IIOX2TQO625Lalh48P2VuD62cjRNIb6vZdQMD2bJJszSSfVdjWAt9hLTc7nRIXT7BDdfrZwVSwHE/1SWCFOsoaXniUc2Ow7+IezVTdCPAGSyh/wsNxrhQBP5sl79h7OLM9jyxgL7g+y65DMRYWudGjUPMcP+9d1dB1FdXwpHGaqmtPQeJ+zEWYb9vpOmlGxcrUBi0rgzAmdSwNDf7C/9tUwIBKlyQCOhaoPKRJCciVu2MVT+ZsB+if7VnT9XrNtznXquoqK9E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
